/**
 * Официально поддерживаемые свойства цветовой темы VS Code
 * Согласно документации: https://code.visualstudio.com/api/references/theme-color
 * Последнее обновление: август 2025
 */

export const VS_CODE_COLOR_KEYS = [
  // Contrast colors
  'contrastActiveBorder',
  'contrastBorder',

  // Base colors
  'focusBorder',
  'foreground',
  'disabledForeground',
  'widget.border',
  'widget.shadow',
  'selection.background',
  'descriptionForeground',
  'errorForeground',
  'icon.foreground',
  'sash.hoverBorder',

  // Window border
  'window.activeBorder',
  'window.inactiveBorder',

  // Text colors
  'textBlockQuote.background',
  'textBlockQuote.border',
  'textCodeBlock.background',
  'textLink.activeForeground',
  'textLink.foreground',
  'textPreformat.foreground',
  'textPreformat.background',
  'textSeparator.foreground',

  // Action colors
  'toolbar.hoverBackground',
  'toolbar.hoverOutline',
  'toolbar.activeBackground',

  // Button control
  'button.background',
  'button.foreground',
  'button.border',
  'button.separator',
  'button.hoverBackground',
  'button.secondaryForeground',
  'button.secondaryBackground',
  'button.secondaryHoverBackground',
  'checkbox.background',
  'checkbox.foreground',
  'checkbox.border',
  'checkbox.selectBackground',
  'checkbox.selectBorder',
  'radio.activeForeground',
  'radio.activeBackground',
  'radio.activeBorder',
  'radio.inactiveForeground',
  'radio.inactiveBackground',
  'radio.inactiveBorder',
  'radio.inactiveHoverBackground',

  // Dropdown control
  'dropdown.background',
  'dropdown.listBackground',
  'dropdown.border',
  'dropdown.foreground',

  // Input control
  'input.background',
  'input.border',
  'input.foreground',
  'input.placeholderForeground',
  'inputOption.activeBackground',
  'inputOption.activeBorder',
  'inputOption.activeForeground',
  'inputOption.hoverBackground',
  'inputValidation.errorBackground',
  'inputValidation.errorForeground',
  'inputValidation.errorBorder',
  'inputValidation.infoBackground',
  'inputValidation.infoForeground',
  'inputValidation.infoBorder',
  'inputValidation.warningBackground',
  'inputValidation.warningForeground',
  'inputValidation.warningBorder',

  // Scrollbar control
  'scrollbar.shadow',
  'scrollbarSlider.activeBackground',
  'scrollbarSlider.background',
  'scrollbarSlider.hoverBackground',

  // Badge
  'badge.foreground',
  'badge.background',

  // Progress bar
  'progressBar.background',

  // Lists and trees
  'list.activeSelectionBackground',
  'list.activeSelectionForeground',
  'list.activeSelectionIconForeground',
  'list.dropBackground',
  'list.focusBackground',
  'list.focusForeground',
  'list.focusHighlightForeground',
  'list.focusOutline',
  'list.focusAndSelectionOutline',
  'list.highlightForeground',
  'list.hoverBackground',
  'list.hoverForeground',
  'list.inactiveSelectionBackground',
  'list.inactiveSelectionForeground',
  'list.inactiveSelectionIconForeground',
  'list.inactiveFocusBackground',
  'list.inactiveFocusOutline',
  'list.invalidItemForeground',
  'list.errorForeground',
  'list.warningForeground',
  'listFilterWidget.background',
  'listFilterWidget.outline',
  'listFilterWidget.noMatchesOutline',
  'listFilterWidget.shadow',
  'list.filterMatchBackground',
  'list.filterMatchBorder',
  'list.deemphasizedForeground',
  'list.dropBetweenBackground',
  'tree.indentGuidesStroke',
  'tree.inactiveIndentGuidesStroke',
  'tree.tableColumnsBorder',
  'tree.tableOddRowsBackground',

  // Activity Bar
  'activityBar.background',
  'activityBar.dropBorder',
  'activityBar.foreground',
  'activityBar.inactiveForeground',
  'activityBar.border',
  'activityBarBadge.background',
  'activityBarBadge.foreground',
  'activityBar.activeBorder',
  'activityBar.activeBackground',
  'activityBar.activeFocusBorder',
  'activityBarTop.foreground',
  'activityBarTop.activeBorder',
  'activityBarTop.inactiveForeground',
  'activityBarTop.dropBorder',
  'activityBarTop.background',
  'activityBarTop.activeBackground',
  'activityWarningBadge.foreground',
  'activityWarningBadge.background',
  'activityErrorBadge.foreground',
  'activityErrorBadge.background',

  // Profiles
  'profileBadge.background',
  'profileBadge.foreground',
  'profiles.sashBorder',

  // Side Bar
  'sideBar.background',
  'sideBar.foreground',
  'sideBar.border',
  'sideBar.dropBackground',
  'sideBarTitle.foreground',
  'sideBarSectionHeader.background',
  'sideBarSectionHeader.foreground',
  'sideBarSectionHeader.border',
  'sideBarActivityBarTop.border',
  'sideBarTitle.background',
  'sideBarTitle.border',
  'sideBarStickyScroll.background',
  'sideBarStickyScroll.border',
  'sideBarStickyScroll.shadow',

  // Minimap
  'minimap.findMatchHighlight',
  'minimap.selectionHighlight',
  'minimap.errorHighlight',
  'minimap.warningHighlight',
  'minimap.background',
  'minimap.selectionOccurrenceHighlight',
  'minimap.foregroundOpacity',
  'minimap.infoHighlight',
  'minimap.chatEditHighlight',
  'minimapSlider.background',
  'minimapSlider.hoverBackground',
  'minimapSlider.activeBackground',
  'minimapGutter.addedBackground',
  'minimapGutter.modifiedBackground',
  'minimapGutter.deletedBackground',

  // Editor Groups & Tabs
  'editorGroup.border',
  'editorGroup.dropBackground',
  'editorGroupHeader.noTabsBackground',
  'editorGroupHeader.tabsBackground',
  'editorGroupHeader.tabsBorder',
  'editorGroupHeader.border',
  'editorGroup.emptyBackground',
  'editorGroup.focusedEmptyBorder',
  'editorGroup.dropIntoPromptForeground',
  'editorGroup.dropIntoPromptBackground',
  'editorGroup.dropIntoPromptBorder',
  'tab.activeBackground',
  'tab.unfocusedActiveBackground',
  'tab.activeForeground',
  'tab.border',
  'tab.activeBorder',
  'tab.selectedBorderTop',
  'tab.selectedBackground',
  'tab.selectedForeground',
  'tab.dragAndDropBorder',
  'tab.unfocusedActiveBorder',
  'tab.activeBorderTop',
  'tab.unfocusedActiveBorderTop',
  'tab.lastPinnedBorder',
  'tab.inactiveBackground',
  'tab.unfocusedInactiveBackground',
  'tab.inactiveForeground',
  'tab.unfocusedActiveForeground',
  'tab.unfocusedInactiveForeground',
  'tab.hoverBackground',
  'tab.unfocusedHoverBackground',
  'tab.hoverForeground',
  'tab.unfocusedHoverForeground',
  'tab.hoverBorder',
  'tab.unfocusedHoverBorder',
  'tab.activeModifiedBorder',
  'tab.inactiveModifiedBorder',
  'tab.unfocusedActiveModifiedBorder',
  'tab.unfocusedInactiveModifiedBorder',
  'editorPane.background',
  'sideBySideEditor.horizontalBorder',
  'sideBySideEditor.verticalBorder',

  // Editor colors
  'editor.background',
  'editor.foreground',
  'editorLineNumber.foreground',
  'editorLineNumber.activeForeground',
  'editorLineNumber.dimmedForeground',
  'editorCursor.background',
  'editorCursor.foreground',
  'editorMultiCursor.primary.foreground',
  'editorMultiCursor.primary.background',
  'editorMultiCursor.secondary.foreground',
  'editorMultiCursor.secondary.background',
  'editor.selectionBackground',
  'editor.selectionForeground',
  'editor.inactiveSelectionBackground',
  'editor.selectionHighlightBackground',
  'editor.selectionHighlightBorder',
  'editor.wordHighlightBackground',
  'editor.wordHighlightBorder',
  'editor.wordHighlightStrongBackground',
  'editor.wordHighlightStrongBorder',
  'editor.wordHighlightTextBackground',
  'editor.wordHighlightTextBorder',
  'editor.findMatchBackground',
  'editor.findMatchForeground',
  'editor.findMatchHighlightBackground',
  'editor.findMatchHighlightForeground',
  'editor.findRangeHighlightBackground',
  'editor.findMatchBorder',
  'editor.findMatchHighlightBorder',
  'editor.findRangeHighlightBorder',
  'search.resultsInfoForeground',
  'searchEditor.findMatchBackground',
  'searchEditor.findMatchBorder',
  'searchEditor.textInputBorder',
  'editor.hoverHighlightBackground',
  'editor.lineHighlightBackground',
  'editor.lineHighlightBorder',
  'editorUnicodeHighlight.border',
  'editorUnicodeHighlight.background',
  'editorLink.activeForeground',
  'editor.rangeHighlightBackground',
  'editor.rangeHighlightBorder',
  // Placeholder text in editor input fields
  'editor.placeholder.foreground',
  'editor.symbolHighlightBackground',
  'editor.symbolHighlightBorder',
  'editorWhitespace.foreground',
  'editorIndentGuide.background',
  'editorIndentGuide.background1',
  'editorIndentGuide.background2',
  'editorIndentGuide.background3',
  'editorIndentGuide.background4',
  'editorIndentGuide.background5',
  'editorIndentGuide.background6',
  'editorIndentGuide.activeBackground',
  'editorIndentGuide.activeBackground1',
  'editorIndentGuide.activeBackground2',
  'editorIndentGuide.activeBackground3',
  'editorIndentGuide.activeBackground4',
  'editorIndentGuide.activeBackground5',
  'editorIndentGuide.activeBackground6',
  'editorInlayHint.background',
  'editorInlayHint.foreground',
  'editorInlayHint.typeForeground',
  'editorInlayHint.typeBackground',
  'editorInlayHint.parameterForeground',
  'editorInlayHint.parameterBackground',
  'editorRuler.foreground',
  'editor.linkedEditingBackground',
  'editorCodeLens.foreground',
  'editorLightBulb.foreground',
  'editorLightBulbAutoFix.foreground',
  'editorLightBulbAi.foreground',
  'editorBracketMatch.background',
  'editorBracketMatch.border',
  'editorBracketHighlight.foreground1',
  'editorBracketHighlight.foreground2',
  'editorBracketHighlight.foreground3',
  'editorBracketHighlight.foreground4',
  'editorBracketHighlight.foreground5',
  'editorBracketHighlight.foreground6',
  'editorBracketHighlight.unexpectedBracket.foreground',
  'editorBracketPairGuide.activeBackground1',
  'editorBracketPairGuide.activeBackground2',
  'editorBracketPairGuide.activeBackground3',
  'editorBracketPairGuide.activeBackground4',
  'editorBracketPairGuide.activeBackground5',
  'editorBracketPairGuide.activeBackground6',
  'editorBracketPairGuide.background1',
  'editorBracketPairGuide.background2',
  'editorBracketPairGuide.background3',
  'editorBracketPairGuide.background4',
  'editorBracketPairGuide.background5',
  'editorBracketPairGuide.background6',
  'editor.foldBackground',
  'editor.foldPlaceholderForeground',
  'editorOverviewRuler.background',
  'editorOverviewRuler.border',
  'editorOverviewRuler.findMatchForeground',
  'editorOverviewRuler.rangeHighlightForeground',
  'editorOverviewRuler.selectionHighlightForeground',
  'editorOverviewRuler.wordHighlightForeground',
  'editorOverviewRuler.wordHighlightStrongForeground',
  'editorOverviewRuler.wordHighlightTextForeground',
  'editorOverviewRuler.modifiedForeground',
  'editorOverviewRuler.addedForeground',
  'editorOverviewRuler.deletedForeground',
  'editorOverviewRuler.errorForeground',
  'editorOverviewRuler.warningForeground',
  'editorOverviewRuler.infoForeground',
  'editorOverviewRuler.bracketMatchForeground',
  'editorError.foreground',
  'editorError.border',
  'editorError.background',
  'editorWarning.foreground',
  'editorWarning.border',
  'editorWarning.background',
  'editorInfo.foreground',
  'editorInfo.border',
  'editorInfo.background',
  'editorHint.foreground',
  'editorHint.border',
  'problemsErrorIcon.foreground',
  'problemsWarningIcon.foreground',
  'problemsInfoIcon.foreground',
  'editorUnnecessaryCode.border',
  'editorUnnecessaryCode.opacity',
  'editorGutter.background',
  'editorGutter.modifiedBackground',
  'editorGutter.addedBackground',
  'editorGutter.deletedBackground',
  'editorGutter.commentRangeForeground',
  'editorGutter.commentGlyphForeground',
  'editorGutter.commentUnresolvedGlyphForeground',
  'editorGutter.foldingControlForeground',
  'editorCommentsWidget.resolvedBorder',
  'editorCommentsWidget.unresolvedBorder',
  'editorCommentsWidget.rangeBackground',
  'editorCommentsWidget.rangeActiveBackground',
  'editorCommentsWidget.replyInputBackground',
  'editorStickyScroll.background',
  'editorStickyScroll.border',
  'editorStickyScroll.shadow',
  'editorStickyScrollHover.background',

  // Diff editor colors
  'diffEditor.insertedTextBackground',
  'diffEditor.insertedTextBorder',
  'diffEditor.removedTextBackground',
  'diffEditor.removedTextBorder',
  'diffEditor.border',
  'diffEditor.diagonalFill',
  'diffEditor.insertedLineBackground',
  'diffEditor.removedLineBackground',
  'diffEditorGutter.insertedLineBackground',
  'diffEditorGutter.removedLineBackground',
  'diffEditorOverview.insertedForeground',
  'diffEditorOverview.removedForeground',
  'diffEditor.unchangedRegionBackground',
  'diffEditor.unchangedRegionForeground',
  'diffEditor.unchangedRegionShadow',
  'diffEditor.unchangedCodeBackground',
  'diffEditor.move.border',
  'diffEditor.moveActive.border',

  // Chat colors
  'chat.requestBorder',
  'chat.requestBackground',
  'chat.slashCommandBackground',
  'chat.slashCommandForeground',
  'chat.avatarBackground',
  'chat.avatarForeground',

  // Inline Chat colors
  'inlineChat.background',
  'inlineChat.foreground',
  'inlineChat.border',
  'inlineChat.shadow',
  'inlineChatInput.border',
  'inlineChatInput.focusBorder',
  'inlineChatInput.placeholderForeground',
  'inlineChatInput.background',
  'inlineChatDiff.inserted',
  'inlineChatDiff.removed',

  // Panel Chat colors
  'interactive.activeCodeBorder',
  'interactive.inactiveCodeBorder',

  // Editor widget colors
  'editorWidget.foreground',
  'editorWidget.background',
  'editorWidget.border',
  'editorWidget.resizeBorder',
  'editorSuggestWidget.background',
  'editorSuggestWidget.border',
  'editorSuggestWidget.foreground',
  'editorSuggestWidget.focusHighlightForeground',
  'editorSuggestWidget.highlightForeground',
  'editorSuggestWidget.selectedBackground',
  'editorSuggestWidget.selectedForeground',
  'editorSuggestWidget.selectedIconForeground',
  'editorSuggestWidgetStatus.foreground',
  'editorHoverWidget.foreground',
  'editorHoverWidget.background',
  'editorHoverWidget.border',
  'editorHoverWidget.highlightForeground',
  'editorHoverWidget.statusBarBackground',
  'editorGhostText.border',
  'editorGhostText.background',
  'editorGhostText.foreground',
  'debugExceptionWidget.background',
  'debugExceptionWidget.border',
  'editorMarkerNavigation.background',
  'editorMarkerNavigationError.background',
  'editorMarkerNavigationWarning.background',
  'editorMarkerNavigationInfo.background',
  'editorMarkerNavigationError.headerBackground',
  'editorMarkerNavigationWarning.headerBackground',
  'editorMarkerNavigationInfo.headerBackground',

  // Peek view colors
  'peekView.border',
  'peekViewEditor.background',
  'peekViewEditorGutter.background',
  'peekViewEditor.matchHighlightBackground',
  'peekViewEditor.matchHighlightBorder',
  'peekViewResult.background',
  'peekViewResult.fileForeground',
  'peekViewResult.lineForeground',
  'peekViewResult.matchHighlightBackground',
  'peekViewResult.selectionBackground',
  'peekViewResult.selectionForeground',
  'peekViewTitle.background',
  'peekViewTitleDescription.foreground',
  'peekViewTitleLabel.foreground',

  // Merge conflicts colors
  'merge.currentHeaderBackground',
  'merge.currentContentBackground',
  'merge.incomingHeaderBackground',
  'merge.incomingContentBackground',
  'merge.border',
  'merge.commonContentBackground',
  'merge.commonHeaderBackground',
  'editorOverviewRuler.currentContentForeground',
  'editorOverviewRuler.incomingContentForeground',
  'editorOverviewRuler.commonContentForeground',
  'editorOverviewRuler.commentForeground',
  'editorOverviewRuler.commentUnresolvedForeground',
  'mergeEditor.change.background',
  'mergeEditor.change.word.background',
  'mergeEditor.conflict.unhandledUnfocused.border',
  'mergeEditor.conflict.unhandledFocused.border',
  'mergeEditor.conflict.handledUnfocused.border',
  'mergeEditor.conflict.handledFocused.border',
  'mergeEditor.conflict.handled.minimapOverViewRuler',
  'mergeEditor.conflict.unhandled.minimapOverViewRuler',
  'mergeEditor.conflictingLines.background',
  'mergeEditor.changeBase.background',
  'mergeEditor.changeBase.word.background',
  'mergeEditor.conflict.input1.background',
  'mergeEditor.conflict.input2.background',

  // Panel colors
  'panel.background',
  'panel.border',
  'panel.dropBorder',
  'panelTitle.activeBorder',
  'panelTitle.activeForeground',
  'panelTitle.inactiveForeground',
  'panelTitle.border',
  'panelTitleBadge.background',
  'panelTitleBadge.foreground',
  'panelInput.border',
  'panelSection.border',
  'panelSection.dropBackground',
  'panelSectionHeader.background',
  'panelSectionHeader.foreground',
  'panelSectionHeader.border',
  // Panel sticky scroll
  'panelStickyScroll.background',
  'panelStickyScroll.border',

  // Status Bar colors
  'statusBar.background',
  'statusBar.foreground',
  'statusBar.border',
  'statusBar.debuggingBackground',
  'statusBar.debuggingForeground',
  'statusBar.debuggingBorder',
  'statusBar.noFolderForeground',
  'statusBar.noFolderBackground',
  'statusBar.noFolderBorder',
  'statusBarItem.activeBackground',
  'statusBarItem.hoverForeground',
  'statusBarItem.hoverBackground',
  'statusBarItem.prominentForeground',
  'statusBarItem.prominentBackground',
  'statusBarItem.prominentHoverForeground',
  'statusBarItem.prominentHoverBackground',
  'statusBarItem.remoteBackground',
  'statusBarItem.remoteForeground',
  'statusBarItem.remoteHoverBackground',
  'statusBarItem.remoteHoverForeground',
  'statusBarItem.errorBackground',
  'statusBarItem.errorForeground',
  'statusBarItem.errorHoverBackground',
  'statusBarItem.errorHoverForeground',
  'statusBarItem.warningBackground',
  'statusBarItem.warningForeground',
  'statusBarItem.warningHoverBackground',
  'statusBarItem.warningHoverForeground',
  'statusBarItem.compactHoverBackground',
  'statusBarItem.focusBorder',
  'statusBar.focusBorder',
  'statusBarItem.offlineBackground',
  'statusBarItem.offlineForeground',
  'statusBarItem.offlineHoverForeground',
  'statusBarItem.offlineHoverBackground',

  // Title Bar colors
  'titleBar.activeBackground',
  'titleBar.activeForeground',
  'titleBar.inactiveBackground',
  'titleBar.inactiveForeground',
  'titleBar.border',

  // Menu Bar colors
  'menubar.selectionForeground',
  'menubar.selectionBackground',
  'menubar.selectionBorder',
  'menu.foreground',
  'menu.background',
  'menu.selectionForeground',
  'menu.selectionBackground',
  'menu.selectionBorder',
  'menu.separatorBackground',
  'menu.border',

  // Command Center colors
  'commandCenter.foreground',
  'commandCenter.activeForeground',
  'commandCenter.background',
  'commandCenter.activeBackground',
  'commandCenter.border',
  'commandCenter.inactiveForeground',
  'commandCenter.inactiveBorder',
  'commandCenter.activeBorder',
  'commandCenter.debuggingBackground',

  // Notification colors
  'notificationCenter.border',
  'notificationCenterHeader.foreground',
  'notificationCenterHeader.background',
  'notificationToast.border',
  'notifications.foreground',
  'notifications.background',
  'notifications.border',
  'notificationLink.foreground',
  'notificationsErrorIcon.foreground',
  'notificationsWarningIcon.foreground',
  'notificationsInfoIcon.foreground',

  // Banner colors
  'banner.background',
  'banner.foreground',
  'banner.iconForeground',

  // Extensions colors
  'extensionButton.prominentForeground',
  'extensionButton.prominentBackground',
  'extensionButton.prominentHoverBackground',
  'extensionButton.background',
  'extensionButton.foreground',
  'extensionButton.hoverBackground',
  'extensionButton.separator',
  'extensionBadge.remoteBackground',
  'extensionBadge.remoteForeground',
  'extensionIcon.starForeground',
  'extensionIcon.verifiedForeground',
  'extensionIcon.preReleaseForeground',
  'extensionIcon.sponsorForeground',

  // Quick picker colors
  'pickerGroup.border',
  'pickerGroup.foreground',
  'quickInput.background',
  'quickInput.foreground',
  'quickInputList.focusBackground',
  'quickInputList.focusForeground',
  'quickInputList.focusIconForeground',
  'quickInputTitle.background',

  // Keybinding label colors
  'keybindingLabel.background',
  'keybindingLabel.foreground',
  'keybindingLabel.border',
  'keybindingLabel.bottomBorder',

  // Keyboard shortcut table colors
  'keybindingTable.headerBackground',
  'keybindingTable.rowsBackground',

  // Integrated Terminal colors
  'terminal.background',
  'terminal.border',
  'terminal.foreground',
  'terminal.ansiBlack',
  'terminal.ansiBlue',
  'terminal.ansiBrightBlack',
  'terminal.ansiBrightBlue',
  'terminal.ansiBrightCyan',
  'terminal.ansiBrightGreen',
  'terminal.ansiBrightMagenta',
  'terminal.ansiBrightRed',
  'terminal.ansiBrightWhite',
  'terminal.ansiBrightYellow',
  'terminal.ansiCyan',
  'terminal.ansiGreen',
  'terminal.ansiMagenta',
  'terminal.ansiRed',
  'terminal.ansiWhite',
  'terminal.ansiYellow',
  'terminal.selectionBackground',
  'terminal.selectionForeground',
  'terminal.inactiveSelectionBackground',
  'terminal.findMatchBackground',
  'terminal.findMatchBorder',
  'terminal.findMatchHighlightBackground',
  'terminal.findMatchHighlightBorder',
  'terminal.hoverHighlightBackground',
  'terminalCursor.background',
  'terminalCursor.foreground',
  'terminal.dropBackground',
  'terminal.tab.activeBorder',
  'terminalCommandDecoration.defaultBackground',
  'terminalCommandDecoration.successBackground',
  'terminalCommandDecoration.errorBackground',
  'terminalOverviewRuler.cursorForeground',
  'terminalOverviewRuler.findMatchForeground',

  // Debug colors
  'debugToolBar.background',
  'debugToolBar.border',
  'editor.stackFrameHighlightBackground',
  'editor.focusedStackFrameHighlightBackground',
  'editor.inlineValuesForeground',
  'editor.inlineValuesBackground',
  'debugView.exceptionLabelForeground',
  'debugView.exceptionLabelBackground',
  'debugView.stateLabelForeground',
  'debugView.stateLabelBackground',
  'debugView.valueChangedHighlight',
  'debugTokenExpression.name',
  'debugTokenExpression.value',
  'debugTokenExpression.string',
  'debugTokenExpression.boolean',
  'debugTokenExpression.number',
  'debugTokenExpression.error',

  // Testing colors
  'testing.runAction',
  'testing.iconErrored',
  'testing.iconFailed',
  'testing.iconPassed',
  'testing.iconQueued',
  'testing.iconUnset',
  'testing.iconSkipped',
  'testing.peekBorder',
  'testing.peekHeaderBackground',
  'testing.message.error.lineBackground',
  'testing.message.info.decorationForeground',
  'testing.message.info.lineBackground',
  'testing.messagePeekBorder',
  'testing.messagePeekHeaderBackground',

  // Welcome page colors
  'welcomePage.background',
  'welcomePage.progress.background',
  'welcomePage.progress.foreground',
  'welcomePage.tileBackground',
  'welcomePage.tileHoverBackground',
  'welcomePage.tileBorder',
  'walkThrough.embeddedEditorBackground',

  // Git colors
  // Git blame annotations in editor
  'git.blame.editorDecorationForeground',
  'gitDecoration.addedResourceForeground',
  'gitDecoration.modifiedResourceForeground',
  'gitDecoration.deletedResourceForeground',
  'gitDecoration.renamedResourceForeground',
  'gitDecoration.stageModifiedResourceForeground',
  'gitDecoration.stageDeletedResourceForeground',
  'gitDecoration.untrackedResourceForeground',
  'gitDecoration.ignoredResourceForeground',
  'gitDecoration.conflictingResourceForeground',
  'gitDecoration.submoduleResourceForeground',

  // SCM Graph colors
  'scmGraph.historyItemHoverDefaultLabelForeground',
  'scmGraph.historyItemHoverLabelForeground',
  'scmGraph.foreground1',
  'scmGraph.foreground2',
  'scmGraph.foreground3',
  'scmGraph.foreground4',
  'scmGraph.foreground5',
  'scmGraph.historyItemHoverAdditionsForeground',
  'scmGraph.historyItemHoverDeletionsForeground',
  'scmGraph.historyItemRefColor',
  'scmGraph.historyItemRemoteRefColor',
  'scmGraph.historyItemBaseRefColor',

  // Settings Editor colors
  'settings.headerForeground',
  'settings.modifiedItemIndicator',
  'settings.dropdownBackground',
  'settings.dropdownForeground',
  'settings.dropdownBorder',
  'settings.dropdownListBorder',
  'settings.checkboxBackground',
  'settings.checkboxForeground',
  'settings.checkboxBorder',
  'settings.rowHoverBackground',
  'settings.textInputBackground',
  'settings.textInputForeground',
  'settings.textInputBorder',
  'settings.numberInputBackground',
  'settings.numberInputForeground',
  'settings.numberInputBorder',
  'settings.focusedRowBackground',
  'settings.focusedRowBorder',
  'settings.headerBorder',
  'settings.sashBorder',
  'settings.settingsHeaderHoverForeground',

  // Breadcrumbs colors
  'breadcrumb.foreground',
  'breadcrumb.background',
  'breadcrumb.focusForeground',
  'breadcrumb.activeSelectionForeground',
  'breadcrumbPicker.background',

  // Snippets colors
  'editor.snippetTabstopHighlightBackground',
  'editor.snippetTabstopHighlightBorder',
  'editor.snippetFinalTabstopHighlightBackground',
  'editor.snippetFinalTabstopHighlightBorder',

  // Symbol Icons colors
  'symbolIcon.arrayForeground',
  'symbolIcon.booleanForeground',
  'symbolIcon.classForeground',
  'symbolIcon.colorForeground',
  'symbolIcon.constantForeground',
  'symbolIcon.constructorForeground',
  'symbolIcon.enumeratorForeground',
  'symbolIcon.enumeratorMemberForeground',
  'symbolIcon.eventForeground',
  'symbolIcon.fieldForeground',
  'symbolIcon.fileForeground',
  'symbolIcon.folderForeground',
  'symbolIcon.functionForeground',
  'symbolIcon.interfaceForeground',
  'symbolIcon.keyForeground',
  'symbolIcon.keywordForeground',
  'symbolIcon.methodForeground',
  'symbolIcon.moduleForeground',
  'symbolIcon.namespaceForeground',
  'symbolIcon.nullForeground',
  'symbolIcon.numberForeground',
  'symbolIcon.objectForeground',
  'symbolIcon.operatorForeground',
  'symbolIcon.packageForeground',
  'symbolIcon.propertyForeground',
  'symbolIcon.referenceForeground',
  'symbolIcon.snippetForeground',
  'symbolIcon.stringForeground',
  'symbolIcon.structForeground',
  'symbolIcon.textForeground',
  'symbolIcon.typeParameterForeground',
  'symbolIcon.unitForeground',
  'symbolIcon.variableForeground',

  // Debug Icons colors
  'debugIcon.breakpointForeground',
  'debugIcon.breakpointDisabledForeground',
  'debugIcon.breakpointUnverifiedForeground',
  'debugIcon.breakpointCurrentStackframeForeground',
  'debugIcon.breakpointStackframeForeground',
  'debugIcon.startForeground',
  'debugIcon.pauseForeground',
  'debugIcon.stopForeground',
  'debugIcon.disconnectForeground',
  'debugIcon.restartForeground',
  'debugIcon.stepOverForeground',
  'debugIcon.stepIntoForeground',
  'debugIcon.stepOutForeground',
  'debugIcon.continueForeground',
  'debugIcon.stepBackForeground',
  'debugConsole.infoForeground',
  'debugConsole.warningForeground',
  'debugConsole.errorForeground',
  'debugConsole.sourceForeground',
  'debugConsoleInputIcon.foreground',

  // Notebook colors
  'notebook.editorBackground',
  'notebook.cellBorderColor',
  'notebook.cellHoverBackground',
  'notebook.cellInsertionIndicator',
  'notebook.cellStatusBarItemHoverBackground',
  'notebook.cellToolbarSeparator',
  'notebook.cellEditorBackground',
  'notebook.focusedCellBackground',
  'notebook.focusedCellBorder',
  'notebook.focusedEditorBorder',
  'notebook.inactiveFocusedCellBorder',
  'notebook.inactiveSelectedCellBorder',
  'notebook.outputContainerBackgroundColor',
  'notebook.outputContainerBorderColor',
  'notebook.selectedCellBackground',
  'notebook.selectedCellBorder',
  'notebook.symbolHighlightBackground',
  'notebookScrollbarSlider.activeBackground',
  'notebookScrollbarSlider.background',
  'notebookScrollbarSlider.hoverBackground',
  'notebookStatusErrorIcon.foreground',
  'notebookStatusRunningIcon.foreground',
  'notebookStatusSuccessIcon.foreground',
  'notebookEditorOverviewRuler.runningCellForeground',

  // Chart colors
  'charts.foreground',
  'charts.lines',
  'charts.red',
  'charts.blue',
  'charts.yellow',
  'charts.orange',
  'charts.green',
  'charts.purple',

  // Ports colors
  'ports.iconRunningProcessForeground',

  // Comments View colors
  'commentsView.resolvedIcon',
  'commentsView.unresolvedIcon',

  // Action Bar colors
  'actionBar.toggledBackground',

  // Simple Find Widget colors
  'simpleFindWidget.sashBorder',
] as const

export type VSCodeColorKey = typeof VS_CODE_COLOR_KEYS[number]

export const ALLOWED_THEME_PROPERTIES: ReadonlySet<string> = new Set<string>(
  VS_CODE_COLOR_KEYS as unknown as string[]
)

/**
 * Недопустимые/устаревшие свойства, которые нужно избегать
 */
export const DEPRECATED_PROPERTIES = new Set([
  'button.focusBorder', // Не поддерживается
  'input.focusBorder', // Не поддерживается
  'checkbox.focusBorder', // Не поддерживается
  'radio.focusBorder', // Не поддерживается
])

/**
 * Свойства, которые были переименованы
 */
export const RENAMED_PROPERTIES = new Map([
  ['editorActiveLineNumber.foreground', 'editorLineNumber.activeForeground'],
  ['editorCodeLens.foreground', 'editorCodeLens.foreground'],
])
