import type { Palette } from '../types/palette'
import { core } from './core'

const { tokens } = core

export const palette: Palette = {
  bg: {
    base: core.bg.base,
    elevated: core.bg.elevated,
    overlay: core.bg.overlay,
    input: core.bg.input,
    hover: core.bg.hover,
    active: core.bg.active,
    drop: core.bg.drop,
    lineHighlight: core.bg.lineHighlight,
    bracketMatch: core.bg.bracketMatch,
    tabs: core.bg.tabs,
    selection: {
      active: core.bg.selection.active,
      inactive: core.bg.selection.inactive,
      focus: core.bg.selection.focus,
      menu: core.bg.selection.menu,
    },
  },
  line: {
    border: core.border,
    menu: core.border,
  },
  fg: {
    primary: core.text.primary,
    dark: core.bg.base,
    muted: core.text.muted,
    subtle: core.text.subtle,
    inactive: core.text.inactive,
    panelText: core.text.primary,
    soft: core.text.soft,
    selectionText: core.text.selection,
    onSelection: core.text.selection,
    activeTitle: core.text.primary,
    breadcrumb: core.text.primary,
    description: core.text.muted,
  },
  brand: {
    primary: core.accent.cyan,
    button: {
      primary: core.brand.button.primary,
      hover: core.brand.button.hover,
    },
  },
  accent: {
    blue: core.accent.blue,
    cyan: core.accent.cyan,
    teal: tokens.tealSoft,
    magenta: core.accent.magenta,
    // Жёлтый возвращаем к ядру для корректной семантики warning
    yellow: core.accent.yellow,
    orange: tokens.indigo,
    red: core.accent.red,
    purple: core.accent.purple,
  },
  token: {
    comment: core.text.comment,
    commentDoc: core.text.commentDoc,
    commentDocEmphasized: core.text.commentDocEmphasized,
    constant: tokens.skyLight,
    string: core.accent.green,
    color: core.text.subtle2,
    invalid: core.accent.red,
    invalidDeprecated: core.accent.magenta,
    storageType: core.accent.magenta,
    storageModifier: core.accent.purple,
    interpolation: core.accent.cyan,
    templateKeyword: core.accent.teal,
    spread: tokens.rose,
    operator: core.text.muted,
    importExport: core.accent.magenta,
    keyword: core.accent.magenta,
    keywordSql: core.accent.cyan,
    keywordLogical: core.accent.magenta,
    tag: core.accent.blue,
    tagComponent: core.accent.magenta,
    tagPunctuation: core.text.muted,
    globalConstant: tokens.skyLight,
    variable: core.text.primary,
    objectVariable: core.text.primary,
    arrayKey: core.accent.cyan,
    objectKey: core.text.primary,
    objectProperty: core.accent.cyan,
    objectPropertyAlt: core.text.primary,
    objectKeyLevel3: tokens.azureLight,
    cVariable: core.accent.blue,
    otherVariable: core.accent.cyan,
    method: core.accent.blue,
    function: core.accent.blue,
    functionArg: tokens.sky,
    typeConstant: core.accent.magenta,
    variableDefinition: core.accent.magenta,
    inheritedClass: core.accent.magenta,
    classSupport: tokens.tealDeep,
    className: core.text.primary,
    supportFunction: tokens.tealDeep,
    cssProperty: core.accent.blue,
    cssFont: core.accent.green,
    cssClass: core.text.primary,
    cssId: core.accent.magenta,
    cssTag: tokens.tealDeep,
    cssReference: tokens.tealDeep,
    cssPunctuation: tokens.bluePunctuation,
    cssAtRule: tokens.blue400,
    cssParentSelector: core.accent.teal,
    scssMixin: core.accent.magenta,
    scssInclude: core.accent.purple,
    cssValue: tokens.mint,
    languageMethod: core.accent.blue,
    thisKeyword: core.accent.cyan,
    htmlAttribute: core.accent.magenta,
    htmlEntity: tokens.tealDeep,
    vueAttribute: core.accent.magenta,
    cssPseudo: core.accent.magenta,
    markupInserted: tokens.azure,
    markupDeleted: tokens.maroon,
    markupChanged: tokens.blueMuted,
    regex: core.accent.cyan,
    regexGroup: core.accent.purple,
    regexCharClass: core.accent.magenta,
    regexCharSet: tokens.sky,
    regexQuantifier: core.accent.green,
    regexBackslash: core.text.primary,
    escapeChar: core.accent.green,
    decorator: core.accent.blue,
    cssUnit: core.accent.blue,
    jsonKey0: core.accent.blue,
    jsonKey1: tokens.tealDeep,
    jsonKey2: core.accent.cyan,
    jsonKey3: core.accent.magenta,
    jsonKey4: tokens.sky,
    jsonKey5: tokens.tealDeep,
    jsonKey6: core.accent.teal,
    jsonKey7: core.accent.red,
    jsonKey8: core.accent.green,
    plainPunctuation: tokens.bluePunctuation,
    blockPunctuation: tokens.bluePunctuation,
    markdownH1: core.accent.green,
    markdownH2: tokens.blueBright,
    markdownH3: core.accent.blue,
    markdownH4: tokens.blueSoft,
    markdownH5: core.text.subtle2,
    markdownH6: tokens.grayBlue400,
    markdownContent: core.text.primary,
    htmlText: core.text.subtle2,
    markdownRawInline: core.accent.magenta,
    markdownRawPunctuation: core.text.gray600,
    markupItalic: core.text.primary,
    markupBold: core.text.primary,
    markdownBlockquote: core.text.gray600,
    markdownLink: core.accent.teal,
    markdownCodeBlock: core.accent.green,
    markdownSeparator: core.text.gray600,
    markupTable: tokens.blueMuted,
    tokenInfo: core.accent.cyan,
    tokenWarn: tokens.cyan500,
    tokenError: core.accent.red,
    tokenDebug: tokens.lilac,
    apacheTag: core.accent.red,
    preprocessor: core.accent.teal,
    envValue: core.accent.blue,
    ignored: core.text.comment,
    number: tokens.pinkMuted,
    markup: tokens.azure,
    error: tokens.maroon,
    codeBlock: tokens.blueBright,
    linkText: tokens.blueSoft,
    quoteMark: tokens.grayBlue400,
    linkUrl: tokens.blueMuted,
    warning: tokens.cyan500,
    deleted: tokens.redMuted,
    inserted: tokens.lilac,
  },
  ansi: {
    // Корректные ANSI по семантике терминала
    black: core.bg.base,
    brightBlack: core.text.gray600,
    red: core.accent.red,
    brightRed: core.accent.red,
    green: core.accent.green,
    brightGreen: core.accent.green,
    yellow: core.accent.yellow,
    brightYellow: core.accent.yellow,
    blue: core.accent.blue,
    brightBlue: core.accent.blue,
    magenta: core.accent.magenta,
    brightMagenta: core.accent.magenta,
    cyan: core.accent.cyan,
    brightCyan: core.accent.cyan,
    white: core.text.primary,
    brightWhite: core.text.primary,
  },
  ui: {
    description: core.text.primary,
    breadcrumb: core.text.primary,
    shadow: {
      widget: core.ui.shadow,
      scrollbar: core.ui.shadow,
    },
    badge: {
      base: tokens.badgeBase,
      fg: core.bg.base,
    },
    sash: {
      hover: tokens.steelAlt,
    },
    selectionWash: core.ui.selectionWash,
    scrollbarBase: core.ui.scrollbarBase,
    input: {
      placeholder: core.text.placeholder,
      border: core.border,
    },
    list: {
      hoverBg: core.brand.button.hover,
      dropBg: tokens.badgeBase,
    },
    editorLinkActive: core.text.editorLinkActive,
    codeLens: core.accent.blue,
    noMatches: core.accent.blue,
    settingsHeader: tokens.blueMuted,
    window: {
      border: tokens.windowBorder,
    },
    tab: {
      activeBorder: core.accent.blue,
      activeModifiedBorder: tokens.violet,
      inactiveModifiedBorder: tokens.cyan500,
      unfocusedActiveBorder: core.ui.tab.unfocusedActive,
      lastPinnedBorder: tokens.slate,
    },
    statusItem: {
      hover: tokens.steel,
      prominentHover: tokens.steelMuted,
    },
    text: {
      preformat: core.text.preformat,
      separator: tokens.slate,
    },
    debug: {
      exceptionBorder: tokens.brick,
      consoleError: core.accent.red,
      consoleWarning: tokens.cyan500,
      stateLabelBg: core.bg.stateLabel,
      tokenValue: core.text.subtle2,
      tokenString: core.accent.green,
      tokenError: core.accent.red,
      info: core.accent.cyan,
    },
    editorOverview: {
      error: core.accent.red,
      info: core.accent.cyan,
      modified: core.accent.blue,
      added: core.accent.green,
      deleted: core.accent.red,
    },
    gutter: {
      modified: core.accent.blue,
      added: core.accent.green,
      deleted: core.accent.red,
    },
    minimapGutter: {
      modified: core.accent.blue,
      added: core.accent.green,
      deleted: core.accent.red,
    },
    charts: {
      foreground: core.text.subtle2,
    },
    gitlens: {
      foreground: core.text.muted,
    },
    git: {
      ignored: core.ui.git.ignored,
      deleted: core.ui.git.deleted,
      conflicting: core.ui.git.conflicting,
      stageDeleted: core.ui.git.stageDeleted,
      stageModified: core.ui.git.stageModified,
    },
    semantic: {
      white: core.text.primary,
      notificationLink: tokens.blueMuted,
      offline: core.accent.red,
    },
  },
  brackets: {
    round: tokens.bracketRound,
    square: tokens.bracketSquare,
    curly: tokens.bracketCurly,
    angle: tokens.bracketAngle,
  },
  punctuation: {
    comma: tokens.punctuationComma,
    dot: tokens.punctuationDot,
    colon: tokens.punctuationColon,
    semicolon: tokens.punctuationSemicolon,
    operator: tokens.punctuationOperator,
  },
}

// Re-export for convenience in theme modules
export { core }
